# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfcd08fcc86de5d39369ad9d0dd32eb564cd4508ec0ceea1476154db3735cff65f8537bb86646d8cbdfb68786d5f5a6eaf5f3b8a04d47fbd148c73ddc71dd76c

test:
  secret_key_base: ba2e461c30556f529274409ef72530337954b1b91fe4be8235763e33d387d631a776e3e2fb4f24a63c6eedea78ad4203e43b9bc6492ff45037837a55b0a3b00b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
